# Generated by Django 5.1.7 on 2025-10-19 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('M', 'مرد'), ('F', 'زن'), ('O', 'سایر')], max_length=1),
        ),
        migrations.AlterField(
            model_name='patient',
            name='national_id',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='کد ملی باید فقط شامل اعداد باشد', regex='^\\d+$')]),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='شماره تلفن باید در فرمت صحیح وارد شود. حداکثر 15 رقم مجاز است.', regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
