# Generated by Django 5.1.7 on 2025-10-20 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_gender_alter_patient_national_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.CharField(help_text='تاریخ تولد به صورت شمسی (YYYY/MM/DD)', max_length=10),
        ),
        migrations.AlterField(
            model_name='visit',
            name='next_visit_date',
            field=models.CharField(blank=True, help_text='تاریخ ویزیت بعدی به صورت شمسی (YYYY/MM/DD)', max_length=10, null=True),
        ),
    ]
